name: sergiophotography
favicon: null
layout_spectrum: 0.25922
typography_spectrum: 0.0703
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#131722'
    - '#2371e7'
    - '#cf8338'
    - '#6fc8ce'
  brandStrength: 0.6278195
  lightness: 0.2346938
  saturation: 0.7857143
  rhythmicContrast: 0.6932591
purpose: []
