name: sergiophotography
favicon: null
layout_spectrum: 0.99753
typography_spectrum: 0.0703
title: Sergio Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#b1b1b1'
    - '#6c6c6c'
    - '#404040'
  brandStrength: 0.6278195
  lightness: 0.2346938
  saturation: 0.7857143
  rhythmicContrast: 0.6932591
purpose: []
