name: sergiophotography
favicon: null
layout_spectrum: 0.74237
typography_spectrum: 0.0703
title: Sergio Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2e3e5'
    - '#243154'
    - '#eeb621'
    - '#6196be'
    - '#366a99'
  brandStrength: 0.6278195
  lightness: 0.2346938
  saturation: 0.7857143
  rhythmicContrast: 0.6932591
purpose: []
